server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG

app:
  stripe:
    apiKey: ${STRIPE_SECRET_KEY:}
    webhookSecret: ${STRIPE_WEBHOOK_SECRET:}      
